# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(choices=[('v', 'Водка'), ('b', 'Пиво'), ('j', 'Сок'), ('w', 'Вино'), ('l', 'Вино')], max_length=1)),
                ('presence', models.CharField(choices=[('t', 'Приду'), ('f', 'Не приду')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
